/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.toedter.calendar.JDayChooser;
import entity.ChiTietSanPham;
import entity.PhieuGiamGia;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import service.KhuyenMaiService;
import service.ServiceImpl.KhuyenMaiServiceImpl;

/**
 *
 * @author thong
 */
public class KhuyenMaiView extends javax.swing.JPanel {

    /**
     * Creates new form HoanTra
     */
    private KhuyenMaiServiceImpl service = new KhuyenMaiService();
    DefaultTableModel model = new DefaultTableModel();
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    List<ChiTietSanPham> chiTietSanPhams = service.listGetAllCTSP();

    public KhuyenMaiView() {
        initComponents();
        loadTB();
        LoadTBSP();
    }

    public void loadTB() {
        List<PhieuGiamGia> list = service.listGetAll();
        model = (DefaultTableModel) tblKhuyenMai.getModel();
        model.setRowCount(0);
        for (PhieuGiamGia x : list) {
            Object row[] = new Object[]{
                x.getMaPhieu(), x.getTenPhieu(), x.getCtsp().getMaCTSP(), x.getCtsp().getSanPham().getTenSP(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThucGiam() == true ? "Tiền mặt" : " Theo %", formatter.format(x.getGiaTriGiam()), x.getMoTa(), x.getTrangThai() == 0 ? "Hoạt động" : "Ngưng hoạt động"
            };
            model.addRow(row);
        }
    }

    public void LoadTBSP() {
        List<ChiTietSanPham> chiTietSanPhams = service.listGetAllCTSP();
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        for (ChiTietSanPham x : chiTietSanPhams) {
            Object row[] = new Object[]{
                x.getMaCTSP(), x.getSanPham().getTenSP()
            };
            model.addRow(row);
        }
    }

    private double convertedToNumbers(String s) {
        String number = "";
        String[] array = s.replace(".", " ").split("\\s");
        for (String i : array) {
            number = number.concat(i);
        }
        return Double.parseDouble(number);
    }

    private Date forma(String ngay) {
        Date date1 = null;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(ngay);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Ngày chưa được đưa vào input!");
        }
        return date1;
    }

    public boolean checkTenl() {
        if (txtTenKM.getText().matches("[^!,_,-,.,?,|,@,#,$,%,&,*,(,),~, ]+[^0-9]{0,50}")) {
            return true;
        }
        JOptionPane.showMessageDialog(this, "vui lòng nhập đúng Tên");
        return false;
    }

    public boolean check() {

        if (txtTenKM.getText().isEmpty() || txtMoTa.getText().isEmpty() || txtGiaTriGiam.getText().isEmpty() || jDCNgayStart.getDate() == null || jDCNgayEnd.getDate() == null) {
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
            txtTenKM.requestFocus();
            txtMoTa.requestFocus();
            txtGiaTriGiam.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        cboSearch = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDCEnd = new com.toedter.calendar.JDateChooser();
        jDCSearchStart = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTenKM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboHinhThuc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtGiaTriGiam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jDCNgayStart = new com.toedter.calendar.JDateChooser();
        jDCNgayEnd = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rboKHD = new javax.swing.JRadioButton();
        rboHD = new javax.swing.JRadioButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên Khuyên Mãi", "Mã Sản Phẩm", "Tên sản phẩm", "Thời gian bắn đầu", "Thời gian kết thúc", "Hình thức giảm", "Giá trị giảm", "Mô tả", "Trạng thái"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKhuyenMai);

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        cboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm theo tiền", "Giảm theo %" }));
        cboSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSearchItemStateChanged(evt);
            }
        });

        jLabel8.setText("Tìm kiếm:");

        jLabel9.setText("Hình thức giảm");

        jLabel10.setText("Từ ngày");

        jLabel11.setText("Đến ngày");

        btnSearch.setBackground(new java.awt.Color(248, 169, 50));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDCSearchStart, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDCEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnSearch)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(jDCEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCSearchStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Khuyến Mại:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên khuyến mại:");

        cboHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm theo tiền", "Giảm theo %" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hình thức giảm:");

        txtMaKM.setEnabled(false);

        txtGiaTriGiam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaTriGiamKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Giá trị giảm:");

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Thời gian bắt đầu:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Thời gian kết thúc:");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAdd.setBackground(new java.awt.Color(248, 169, 50));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(248, 169, 50));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Làm mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(248, 169, 50));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(248, 169, 50));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate)
                .addGap(34, 34, 34)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(21, 21, 21))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Mô tả:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Trạng thái:");

        buttonGroup1.add(rboKHD);
        rboKHD.setText("Ngưng hoạt động");

        buttonGroup1.add(rboHD);
        rboHD.setSelected(true);
        rboHD.setText("Đang áp dụng");
        rboHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(19, 19, 19)
                                .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rboHD)
                        .addGap(54, 54, 54)
                        .addComponent(rboKHD))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDCNgayEnd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jDCNgayStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cboHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCNgayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jDCNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(rboKHD)
                            .addComponent(rboHD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked

        try {
            List<PhieuGiamGia> giamGias = service.listGetAll();
            int index = tblKhuyenMai.getSelectedRow();
            PhieuGiamGia gia = giamGias.get(index);
            txtMaKM.setText(gia.getMaPhieu());
            txtTenKM.setText(gia.getTenPhieu());
            txtGiaTriGiam.setText(formatter.format(gia.getGiaTriGiam()));
            txtMoTa.setText(gia.getMoTa());
            jDCNgayStart.setDate(forma(gia.getNgayBatDau()));
            jDCNgayEnd.setDate(forma(gia.getNgayKetThuc()));
            if (gia.getHinhThucGiam() == true) {
                cboHinhThuc.setSelectedItem("Giảm theo tiền ");
            } else {
                cboHinhThuc.setSelectedItem("Giảm theo %");
            }
            if (gia.getTrangThai() == 0) {
                rboHD.isSelected();
            } else {
                rboKHD.isSelected();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:'
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");

            if (check() == true) {
                PhieuGiamGia gia = new PhieuGiamGia();
                int index1 = tblSanPham.getSelectedRow();
                String a = tblSanPham.getValueAt(index1, 0).toString();
                if (jDCNgayStart.getDate().before(jDCNgayEnd.getDate()) == false) {
                    Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                    JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải hơn ngày kết thúc!", "Error", JOptionPane.INFORMATION_MESSAGE, icon);
                    return;
                }
                if (service.getOne1(a) != null) {
                    Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                    JOptionPane.showMessageDialog(this, "Sản phẩm này đã có mã giảm giá!", "Error", JOptionPane.INFORMATION_MESSAGE, icon);
                    return;
                } else {
                    gia.setTenPhieu(txtTenKM.getText());
                    gia.setNgayBatDau(sdf.format(jDCNgayStart.getDate()));
                    gia.setNgayKetThuc(sdf.format(jDCNgayEnd.getDate()));
                    if (cboHinhThuc.getSelectedItem().equals("Giảm theo tiền")) {
                        gia.setHinhThucGiam(true);
                    } else {
                        gia.setHinhThucGiam(false);
                    }
                    if (rboHD.isSelected()) {
                        gia.setTrangThai(0);
                    } else {
                        gia.setTrangThai(1);
                    }
                    gia.setGiaTriGiam(convertedToNumbers(txtGiaTriGiam.getText()));
                    gia.setMoTa(txtMoTa.getText());
                    int index = tblSanPham.getSelectedRow();
                    ChiTietSanPham chiTietSanPham = new ChiTietSanPham(tblSanPham.getValueAt(index, 0).toString());
                    gia.setCtsp(chiTietSanPham);
                    service.addPhieuGiamGia(gia);
                    loadTB();
                    cleal();
                    Icon icon = new ImageIcon(getClass().getResource("/iImage/tichxanh.png"));
                    JOptionPane.showMessageDialog(this, "Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE, icon);
                }
            }

        } catch (Exception e) {
            System.out.println(e);
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtGiaTriGiamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaTriGiamKeyReleased
        // TODO add your handling code here:
        try {
            txtGiaTriGiam.setText(formatter.format(convertedToNumbers(txtGiaTriGiam.getText())));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_txtGiaTriGiamKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (check() == true) {
                SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
                PhieuGiamGia gia = new PhieuGiamGia();
                gia.setTenPhieu(txtTenKM.getText());
                gia.setNgayBatDau(sdf.format(jDCNgayStart.getDate()));
                gia.setNgayKetThuc(sdf.format(jDCNgayEnd.getDate()));
                if (cboHinhThuc.getSelectedItem().equals("Giảm theo tiền")) {
                    gia.setHinhThucGiam(true);
                } else {
                    gia.setHinhThucGiam(false);
                }
                if (rboHD.isSelected()) {
                    gia.setTrangThai(0);
                } else {
                    gia.setTrangThai(1);
                }
                gia.setGiaTriGiam(convertedToNumbers(txtGiaTriGiam.getText()));
                gia.setMoTa(txtMoTa.getText());
                int index = tblSanPham.getSelectedRow();
                ChiTietSanPham chiTietSanPham = new ChiTietSanPham(tblSanPham.getValueAt(index, 0).toString());
                gia.setCtsp(chiTietSanPham);
                service.update(gia, txtMaKM.getText());
                loadTB();
                cleal();
                Icon icon = new ImageIcon(getClass().getResource("/iImage/tichxanh.png"));
                JOptionPane.showMessageDialog(this, "Thành Công", "OK", JOptionPane.INFORMATION_MESSAGE, icon);
            }

        } catch (Exception e) {
            System.out.println(e);
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            service.delete(txtMaKM.getText());
            loadTB();
            Icon icon = new ImageIcon(getClass().getResource("/iImage/tichxanh.png"));
            JOptionPane.showMessageDialog(this, "Thành Công", "OK", JOptionPane.INFORMATION_MESSAGE, icon);
        } catch (Exception e) {
            e.printStackTrace();
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtTenKM.setText("");
        txtGiaTriGiam.setText("");
        txtMoTa.setText("");
        txtMaKM.setText("");
        jDCNgayEnd.setDate(null);
        jDCNgayStart.setDate(null);

    }//GEN-LAST:event_btnClearActionPerformed

    private void rboHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rboHDActionPerformed

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        // TODO add your handling code here:
        try {
            String txt = txtSearch.getText().toString();
            List<PhieuGiamGia> list = service.searchTen(txt);
            model = (DefaultTableModel) tblKhuyenMai.getModel();
            model.setRowCount(0);
            for (PhieuGiamGia x : list) {
                Object row[] = new Object[]{
                    x.getMaPhieu(), x.getTenPhieu(), x.getCtsp().getMaCTSP(), x.getCtsp().getSanPham().getTenSP(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThucGiam() == true ? "Tiền mặt" : " Theo %", formatter.format(x.getGiaTriGiam()), x.getMoTa(), x.getTrangThai() == 0 ? "Hoạt động" : "Ngưng hoạt động"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSearchCaretUpdate

    private void cboSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSearchItemStateChanged
        // TODO add your handling code here:
        if (cboSearch.getSelectedItem().equals("Giảm theo tiền")) {
            List<PhieuGiamGia> list = service.searchhtg(true);
            model = (DefaultTableModel) tblKhuyenMai.getModel();
            model.setRowCount(0);
            for (PhieuGiamGia x : list) {
                Object row[] = new Object[]{
                    x.getMaPhieu(), x.getTenPhieu(), x.getCtsp().getMaCTSP(), x.getCtsp().getSanPham().getTenSP(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThucGiam() == true ? "Tiền mặt" : " Theo %", formatter.format(x.getGiaTriGiam()), x.getMoTa(), x.getTrangThai() == 0 ? "Hoạt động" : "Ngưng hoạt động"
                };
                model.addRow(row);
            }
        } else if (cboSearch.getSelectedItem().equals("Giảm theo %")) {
            List<PhieuGiamGia> list = service.searchhtg(false);
            model = (DefaultTableModel) tblKhuyenMai.getModel();
            model.setRowCount(0);
            for (PhieuGiamGia x : list) {
                Object row[] = new Object[]{
                    x.getMaPhieu(), x.getTenPhieu(), x.getCtsp().getMaCTSP(), x.getCtsp().getSanPham().getTenSP(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThucGiam() == true ? "Tiền mặt" : " Theo %", formatter.format(x.getGiaTriGiam()), x.getMoTa(), x.getTrangThai() == 0 ? "Hoạt động" : "Ngưng hoạt động"
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_cboSearchItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            List<PhieuGiamGia> list = service.searchNgay(sdf.format(jDCSearchStart.getDate()), sdf.format(jDCEnd.getDate()));
            model = (DefaultTableModel) tblKhuyenMai.getModel();
            model.setRowCount(0);
            for (PhieuGiamGia x : list) {
                Object row[] = new Object[]{
                    x.getMaPhieu(), x.getTenPhieu(), x.getCtsp().getMaCTSP(), x.getCtsp().getSanPham().getTenSP(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThucGiam() == true ? "Tiền mặt" : " Theo %", formatter.format(x.getGiaTriGiam()), x.getMoTa(), x.getTrangThai() == 0 ? "Hoạt động" : "Ngưng hoạt động"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cleal() {
        txtTenKM.setText("");
        txtGiaTriGiam.setText("");
        txtMoTa.setText("");
        txtMaKM.setText("");
        jDCNgayEnd.setDate(null);
        jDCNgayStart.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboHinhThuc;
    private javax.swing.JComboBox<String> cboSearch;
    private com.toedter.calendar.JDateChooser jDCEnd;
    private com.toedter.calendar.JDateChooser jDCNgayEnd;
    private com.toedter.calendar.JDateChooser jDCNgayStart;
    private com.toedter.calendar.JDateChooser jDCSearchStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rboHD;
    private javax.swing.JRadioButton rboKHD;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaTriGiam;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenKM;
    // End of variables declaration//GEN-END:variables
}
