/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Utilities.DBConnection;
import entity.ChiTietSanPham;
import entity.DangNhap;
import entity.DongSP;
import entity.HoaDon;
import entity.HoaDonChiTiet;
import entity.KHToanCuc;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import service.BanHangService;
import service.ServiceImpl.BanHangServiceImpl;

/**
 *
 * @author thong
 */
public class ViewBanHang extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private BanHangServiceImpl hdsi = new BanHangService();
    private entity.NhanVien nhanVien;
    private DangNhap dangNhap;
    DefaultTableModel model = new DefaultTableModel();
    List<DongSP> listDSP = hdsi.getlistDongsp();
    DefaultComboBoxModel<DongSP> lfdDongSP = new DefaultComboBoxModel<>();
    DecimalFormat formatter = new DecimalFormat("###,###,###");
//    Locale loc = new Locale("vi", "VN");
//    NumberFormat nf = NumberFormat.getCurrencyInstance(loc);

    public ViewBanHang() {
        initComponents();
//        loadTBHD();
        loadCTSPTT();

        lfdDongSP = new DefaultComboBoxModel(listDSP.toArray());
        cboLoai.setSelectedItem("");
        cboLoai.setModel(lfdDongSP);
    }

    private void loadCTSPTT() {
        List<ChiTietSanPham> listCTSP = hdsi.getListCTSPTT();
        model = (DefaultTableModel) tblCTSP.getModel();
        model.setRowCount(0);
        for (ChiTietSanPham x : listCTSP) {
            Object row[] = new Object[]{
                x.getMaCTSP(), x.getSanPham().getTenSP(), x.getMauSac().getTenMS(), x.getChatLieu().getTenCL(), x.getKichThuoc().getTenKT(), x.getDongSP().getTenDongSP(), x.getNsx().getTenNhaSanXuat(), formatter.format(x.getGiaBan()), x.getSoLuongTon(), formatter.format(x.getKhuyenMai())
            };
            model.addRow(row);
        }
    }

    private void loadHDCTTT() {
        List<HoaDonChiTiet> listHDCT = hdsi.getListHDCTTT(Long.parseLong(lblMHD.getText()));
        model = (DefaultTableModel) tblHDCT.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : listHDCT) {
            Object row[] = new Object[]{
                x.getMaHDCTTT(), x.getMaCTSPCT().getMaCTSP(), x.getTenSP(), formatter.format(x.getDonGia()), x.getSoLuong()
            };
            model.addRow(row);
        }
    }

    public void xuatHoaDon(int maHD) {
        try {
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/gui/newReport.jrxml");
            map.put("MaHoaDon", maHD);
            JasperPrint p = JasperFillManager.fillReport(report, map, DBConnection.getConnection());
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTBHD() {
        List<HoaDon> listht = hdsi.getListHDTT();
        model = (DefaultTableModel) tblHD.getModel();
        model.setRowCount(0);
        for (HoaDon x : listht) {
            Object row[] = new Object[]{
                x.getMaHD(), x.getNgayTao(), x.getManhanVien().getTenNV(), x.getMakhachHang().getTenKH()
            };
            model.addRow(row);
        }
        KHToanCuc cuc = new KHToanCuc();
        lblMHD.setText(cuc.getMaHDa());
    }

    public static boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private double convertedToNumbers(String s) {
        String number = "";
        String[] array = s.replace(".", " ").split("\\s");
        for (String i : array) {
            number = number.concat(i);
        }
        return Double.parseDouble(number);
    }

    private String cutChar(String arry) {
        return arry.replaceAll("\\D+", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDCT = new javax.swing.JTable();
        btnxoaGH = new javax.swing.JButton();
        btnxoaGH1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        cboLoai = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMHD = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboHinhThuc = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTienKhach = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnHuyHD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblKH = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblKhuyenMai1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnInsertHD = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày tạo", "Nhân viên", "Khách hàng"
            }
        ));
        tblHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa đơn CT", "Mã sản phầm", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tblHDCT);

        btnxoaGH.setBackground(new java.awt.Color(248, 169, 50));
        btnxoaGH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoaGH.setText("Xóa tất cả");
        btnxoaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaGHActionPerformed(evt);
            }
        });

        btnxoaGH1.setBackground(new java.awt.Color(248, 169, 50));
        btnxoaGH1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoaGH1.setText(" Xóa ");
        btnxoaGH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaGH1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnxoaGH1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnxoaGH)
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnxoaGH1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnxoaGH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Tìm kiếm:");

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Màu sắc", "Chất liệu", "Size", "Loại", "NSX", "Đơn giá", "Số lượng tồn", "Khuyến mại"
            }
        ));
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCTSP);

        cboLoai.setToolTipText("");
        cboLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiItemStateChanged(evt);
            }
        });
        cboLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboLoaiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thanh Toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã khách hàng:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên khách hàng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã hóa đơn:");

        lblMHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMHD.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tổng tiền:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tiền khách đưa:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tiền thừa:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Hình thức thanh toán:");

        cboHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản", " " }));

        jLabel11.setText("VND");

        jLabel13.setText("VND");

        txtTienKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachActionPerformed(evt);
            }
        });
        txtTienKhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Ghi chú:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane4.setViewportView(txtGhiChu);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnHuyHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyHD.setText("Hủy hóa đơn");
        btnHuyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHDActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(248, 169, 50));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnChon.setBackground(new java.awt.Color(248, 169, 50));
        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(248, 169, 50));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Thay Đổi");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblKH.setForeground(new java.awt.Color(204, 0, 0));
        lblKH.setText("KH0002");

        lblTenKH.setForeground(new java.awt.Color(204, 0, 0));
        lblTenKH.setText("Khách lẻ");

        jLabel15.setText("VND");

        lblTongTien.setText("0");

        lblTienThua.setText("0");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Khuyễn mãi");

        lblKhuyenMai.setText("0");

        jLabel12.setText("VND");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tiền cần thanh toán");

        lblKhuyenMai1.setText("0");

        jLabel16.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(36, 36, 36)
                                        .addComponent(cboHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel9))
                                            .addGap(236, 236, 236))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton1)
                                .addGap(149, 149, 149)
                                .addComponent(btnHuyHD))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTienKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMHD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKH))
                    .addComponent(btnChon))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMHD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnHuyHD))
                .addGap(18, 18, 18)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btnInsertHD.setBackground(new java.awt.Color(248, 169, 50));
        btnInsertHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertHD.setText("Tạo Hóa đơn");
        btnInsertHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnInsertHD)
                        .addGap(9, 9, 9))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnInsertHD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertHDActionPerformed
        // TODO add your handling code here:
        try {
            HoaDon don = new HoaDon();
            don.setNgayTao(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date())));
            entity.NhanVien nhanVien1 = new entity.NhanVien(KHToanCuc.getMaNVTC());
            entity.KhachHang hang = new entity.KhachHang(lblKH.getText());
            don.setMakhachHang(hang);
            don.setManhanVien(nhanVien1);
            hdsi.addHDTT(don);
            loadTBHD();
        } catch (Exception e) {
            System.out.println(e);
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }

    }//GEN-LAST:event_btnInsertHDActionPerformed

    private void cboLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboLoaiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiKeyReleased

    private void cboLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiItemStateChanged
        // TODO add your handling code here:
        List<ChiTietSanPham> listCTSP = hdsi.searchLoaiSP(cboLoai.getSelectedItem().toString());
        model = (DefaultTableModel) tblCTSP.getModel();
        model.setRowCount(0);
        for (ChiTietSanPham x : listCTSP) {
            Object row[] = new Object[]{
                x.getMaCTSP(), x.getSanPham().getTenSP(), x.getMauSac().getTenMS(), x.getChatLieu().getTenCL(), x.getKichThuoc().getTenKT(), x.getDongSP().getTenDongSP(), x.getNsx().getTenNhaSanXuat(), formatter.format(x.getGiaBan()), x.getSoLuongTon(), formatter.format(x.getKhuyenMai())
            };
            model.addRow(row);

        }
    }//GEN-LAST:event_cboLoaiItemStateChanged

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked
        // TODO add your handling code here:
        try {
            Integer row1 = tblCTSP.getSelectedRow();
            int soluongTon = (int) tblCTSP.getValueAt(row1, 8);
            if (lblMHD.getText().isEmpty() || Integer.parseInt(lblMHD.getText()) == 0) {
                Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                JOptionPane.showMessageDialog(this, "Chưa có hóa đơn!", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
                return;
            }
            if (soluongTon < 0) {
                Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                JOptionPane.showMessageDialog(this, "Hết hàng !", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
                return;
            }
            Integer row = tblCTSP.getSelectedRow();
            String maCTSP = (String) tblCTSP.getValueAt(row, 0);
            ChiTietSanPham maHDCT = new ChiTietSanPham(maCTSP);
            HoaDon don = new HoaDon(Long.parseLong(lblMHD.getText()));
            String string = (String) tblCTSP.getValueAt(row, 7);
            String soLuongInput = JOptionPane.showInputDialog("Nhập số lượng sản phẩm" + " ");
            if (isNumeric(soLuongInput)) {
                Integer soLuong1 = Integer.parseInt(soLuongInput);
                String maCTSP1 = (String) tblCTSP.getValueAt(row, 0);
                hdsi.updateCTSP(maCTSP1, soLuong1);
                HoaDonChiTiet chiTiet = new HoaDonChiTiet();
                chiTiet.setMaHDCT(don);
                chiTiet.setMaCTSPCT(maHDCT);
                chiTiet.setDonGia(convertedToNumbers(string));
                chiTiet.setSoLuong(soLuong1);
                hdsi.addHDCTTT(chiTiet);
                int khuyenmai = hdsi.getKhuyenMai(Long.parseLong(lblMHD.getText()));
                int tongtientt = hdsi.getTongTien(Long.parseLong(lblMHD.getText()));
                lblTongTien.setText(formatter.format(tongtientt));
                lblKhuyenMai.setText(formatter.format(khuyenmai));
                int tien = tongtientt - khuyenmai;
                lblKhuyenMai1.setText(formatter.format(tien));
                loadHDCTTT();
                loadCTSPTT();
            } else {
                Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                JOptionPane.showMessageDialog(this, "Nhập đúng số lượng", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
            }
        } catch (Exception e) {
            System.out.println(e);
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_tblCTSPMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        // TODO add your handling code here:
        if (txtSearch.getText().length() == 0) {
            loadCTSPTT();
        } else {
            List<ChiTietSanPham> listCTSP = hdsi.searchTenSP(txtSearch.getText());
            model = (DefaultTableModel) tblCTSP.getModel();
            model.setRowCount(0);
            for (ChiTietSanPham x : listCTSP) {
                Object row[] = new Object[]{
                    x.getMaCTSP(), x.getSanPham().getTenSP(), x.getMauSac().getTenMS(), x.getChatLieu().getTenCL(), x.getKichThuoc().getTenKT(), x.getDongSP().getTenDongSP(), x.getNsx().getTenNhaSanXuat(), formatter.format(x.getGiaBan()), x.getSoLuongTon(), formatter.format(x.getKhuyenMai())
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void btnxoaGH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaGH1ActionPerformed
        // TODO add your handling code here:
        try {
            Integer row = tblHDCT.getRowCount();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Không có sản phầm trong table");
                return;
            } else {
                int result = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc muốn xóa sản phẩm",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    Integer ma = tblHDCT.getSelectedRow();

                    hdsi.updateCTSPfromHDCT(tblHDCT.getValueAt(ma, 1).toString(), Long.parseLong(tblHDCT.getValueAt(ma, 0).toString()));
                    hdsi.deletemotHDCT(Long.parseLong(tblHDCT.getValueAt(ma, 0).toString()));
                    int khuyenmai = hdsi.getKhuyenMai(Long.parseLong(lblMHD.getText()));
                    int tongtientt = hdsi.getTongTien(Long.parseLong(lblMHD.getText()));
                    lblTongTien.setText(formatter.format(tongtientt));
                    lblKhuyenMai.setText(formatter.format(khuyenmai));
                    int tien = tongtientt - khuyenmai;
                    lblKhuyenMai1.setText(formatter.format(tien));
                    loadHDCTTT();
                    loadCTSPTT();
                } else if (result == JOptionPane.NO_OPTION) {
                    return;
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnxoaGH1ActionPerformed

    private void btnxoaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaGHActionPerformed
        // TODO add your handling code here:
        try {
            Integer row = tblHDCT.getRowCount();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Không có sản phầm trong table");
                return;
            } else {
                int result = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc muốn xóa sản phẩm",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    Long ma = Long.parseLong(lblMHD.getText());
                    hdsi.deleteHDCTTT(ma);
                    loadHDCTTT();
                    lblKhuyenMai.setText("0");
                    lblTongTien.setText("0");
                    lblKhuyenMai1.setText("0");
                    lblTienThua.setText("0");
                    txtTienKhach.setText("");
                } else if (result == JOptionPane.NO_OPTION) {
                    return;
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnxoaGHActionPerformed

    private void tblHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDMouseClicked
        // TODO add your handling code here:

        Integer index = tblHD.getSelectedRow();
        Long mahdd = (Long) tblHD.getValueAt(index, 0);
        List<HoaDonChiTiet> listHDCT = hdsi.getListHDCTTT1(mahdd);
        model = (DefaultTableModel) tblHDCT.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : listHDCT) {
            Object row[] = new Object[]{
                x.getMaHDCTTT(), x.getMaCTSPCT().getMaCTSP(), x.getTenSP(), formatter.format(x.getDonGia()), x.getSoLuong()
            };
            model.addRow(row);
        }
        List<HoaDon> dons = hdsi.getListHDTT();
        HoaDon h = dons.get(index);
        lblKH.setText(h.getMakhachHang().getMaKH());
        lblTenKH.setText(h.getMakhachHang().getTenKH());
        lblMHD.setText(String.valueOf(mahdd));
        int khuyenmai = hdsi.getKhuyenMai(Long.parseLong(lblMHD.getText()));
        int tongtientt = hdsi.getTongTien(Long.parseLong(lblMHD.getText()));
        lblTongTien.setText(formatter.format(tongtientt));
        lblKhuyenMai.setText(formatter.format(khuyenmai));
        int tien = tongtientt - khuyenmai;
        lblKhuyenMai1.setText(formatter.format(tien));
    }//GEN-LAST:event_tblHDMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            if (tblHD.getRowCount() > 0) {
                Integer row = tblHD.getSelectedRow();
                KHToanCuc cuc = new KHToanCuc();
                lblKH.setText(cuc.getMaKHTC());
                lblTenKH.setText(cuc.getTenKHTC());
                HoaDon don = new HoaDon();
                don.setMaHD(Long.parseLong(tblHD.getValueAt(row, 0).toString()));
                don.setNgayTao(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date())));
                entity.NhanVien nhanVien1 = new entity.NhanVien(KHToanCuc.getMaNVTC());
                entity.KhachHang hang = new entity.KhachHang(cuc.getMaKHTC());
                don.setMakhachHang(hang);
                don.setManhanVien(nhanVien1);
                hdsi.updateHDTT(don);
                loadTBHD();
                Icon icon = new ImageIcon(getClass().getResource("/iImage/tichxanh.png"));
                JOptionPane.showMessageDialog(this, "Thay đổi khách hàng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE, icon);
            } else {
//                KHToanCuc cuc = new KHToanCuc();
//                lblKH.setText(cuc.getMaKHTC());
//                lblTenKH.setText(cuc.getTenKHTC());
                Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
                JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        try {
            formKHHD hD = new formKHHD();
            hD.show();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        try {
            Integer row = tblHD.getSelectedRow();
            HoaDon don = new HoaDon();
            KHToanCuc cuc = new KHToanCuc();
            entity.NhanVien nhanVien1 = new entity.NhanVien(cuc.getMaNVTC());
            entity.KhachHang hang = new entity.KhachHang(lblKH.getText());
            don.setMaHD(Long.parseLong(lblMHD.getText()));
            don.setNgayThanhToan(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date())));
            don.setMakhachHang(hang);
            don.setTinhTrang(1);
            don.setManhanVien(nhanVien1);
            don.setPhuongThucThanhToan(cboHinhThuc.getSelectedItem().toString());

            don.setTongTien(convertedToNumbers(lblTongTien.getText()));
            don.setTienThua(convertedToNumbers(lblTienThua.getText()));
            don.setThanhToan(convertedToNumbers(lblKhuyenMai1.getText()));
            don.setGhiChu(txtGhiChu.getText());

            if (convertedToNumbers(lblTienThua.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng thanh toán đủ tiền");

            } else if (txtTienKhach.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng thanh toán đủ tiền");

            } else {
                HoaDonChiTiet chiTiet = new HoaDonChiTiet();
                HoaDon don1 = new HoaDon(Long.parseLong(lblMHD.getText()));
                chiTiet.setMaHDCT(don1);
                hdsi.editHDCTTT(chiTiet);
                hdsi.editHDTT(don);
                loadTBHD();
                loadHDCTTT();
                Icon icon = new ImageIcon(getClass().getResource("/iImage/tichxanh.png"));
                JOptionPane.showMessageDialog(this, "Thanh Toán Thành Công", "Thông báo", JOptionPane.INFORMATION_MESSAGE, icon);
                xuatHoaDon(Integer.parseInt(lblMHD.getText()));
                lblMHD.setText("0");
                txtGhiChu.setText("");
                txtTienKhach.setText("");
                lblKhuyenMai.setText("0");
                lblTongTien.setText("0");
                lblKhuyenMai1.setText("0");
                lblTienThua.setText("0");
            }
        } catch (Exception e) {
            System.out.println(e);
            Icon icon = new ImageIcon(getClass().getResource("/iImage/Exitmini.png"));
            JOptionPane.showMessageDialog(this, "Thất bại", "Lỗi", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnHuyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHDActionPerformed
        // TODO add your handling code here
        try {
            Integer index = tblHD.getRowCount();
            Integer indexx = tblHDCT.getRowCount();
            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Không có hóa đơn");
                return;
            } else if (indexx < 0) {
                int result = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc muốn hủy hóa đơn",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    Integer row = tblHD.getSelectedRow();
                    Long ma = Long.parseLong(lblMHD.getText());
                    hdsi.deleteHD(ma);
                    loadTBHD();
                    lblMHD.setText("0");
                    lblTenKH.setText("Khách lẻ");
                    lblKH.setText("KH0002");
                    txtGhiChu.setText("");
                    txtTienKhach.setText("");
                    lblKhuyenMai.setText("0");
                    lblTongTien.setText("0");
                    lblKhuyenMai1.setText("0");
                    lblTienThua.setText("0");
                } else if (result == JOptionPane.NO_OPTION) {
                    return;
                }
            } else {
                int result = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc muốn xóa hóa đơn",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    Integer row = tblHD.getSelectedRow();
                    Long ma = Long.parseLong(lblMHD.getText());
                    hdsi.deleteHD(ma);
                    hdsi.deleteHDCT(ma);
                    loadTBHD();
                    loadHDCTTT();
                    lblMHD.setText("0");
                    txtGhiChu.setText("");
                    lblTenKH.setText("Khách lẻ");
                    lblKH.setText("KH0002");
                    txtTienKhach.setText("0");
                    lblKhuyenMai.setText("0");
                    lblTongTien.setText("0");
                    lblKhuyenMai1.setText("0");
                    lblTienThua.setText("0");
                } else if (result == JOptionPane.NO_OPTION) {
                    return;
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnHuyHDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        txtGhiChu.setText("");
        txtTienKhach.setText("0");
        lblKhuyenMai.setText("0");
        lblTongTien.setText("0");
        lblKhuyenMai1.setText("0");
        lblTienThua.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTienKhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachKeyReleased
        // TODO add your handling code here:
        try {
            txtTienKhach.setText(formatter.format(convertedToNumbers(txtTienKhach.getText())));
            String tienTra = txtTienKhach.getText();
            String[] tienthanhtoan = lblKhuyenMai1.getText().split("\\s");
            double tienthua = convertedToNumbers(tienTra) - convertedToNumbers(tienthanhtoan[0]);
            lblTienThua.setText(formatter.format(tienthua));
        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_txtTienKhachKeyReleased

    private void txtTienKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHuyHD;
    private javax.swing.JButton btnInsertHD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnxoaGH;
    private javax.swing.JButton btnxoaGH1;
    private javax.swing.JComboBox<String> cboHinhThuc;
    private javax.swing.JComboBox cboLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblKhuyenMai1;
    private javax.swing.JLabel lblMHD;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblCTSP;
    private javax.swing.JTable tblHD;
    private javax.swing.JTable tblHDCT;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTienKhach;
    // End of variables declaration//GEN-END:variables
}
